### ISSUE TITLE
Idea: RangeFrom

### ISSUE THREAD

**Issue by CAD97** [rust-analyzer/text_unit#15]
If we reserve `u32::MAX` to mean unbounded, we can have `TextRange::from(size) => size..` and `TextRange::to(size) => 0..size`. (The lower unbound can just be immediately normalized to `0`.)

**Comment by matklad** [comment]
> `TextRange::from(size)`

This is objectively horrible, because it's not `From::from` :)

**Comment by CAD97** [comment]
yeah I realize that now but ignore the naming is the underlying concept good/bad/meh/worth-it/not

**Comment by matklad** [comment]
Another problem with treating `u32` as unbounded is that it adds semi-infitite ranges. And that makes usages of TextRange harder: even `len` then should return an `Option<TextSize>`.

**Comment by CAD97** [comment]
Still, one of the main uses of the `TextUnit->usize` escape hatch in ra is `RangeFrom`... if only we could let `string[TextSize..]` work... `SliceIndex` is actually stable, it's just sealed. [I asked about it](https://github.com/rust-lang/rust/issues/35729#issuecomment-598777102), but obviously an implementable `SliceIndex` is a while away even if desirable.
