### ISSUE TITLE
Is our current TextSized for &str the desired behavior?

### ISSUE THREAD

**Issue by CAD97** [rust-analyzer/text_unit#19]
```rust
/// This will panic for strings larger than `TextSize::MAX` when
/// debug assertions are enabled, and wrap when they are disabled.
impl TextSized for &'_ str {
    #[inline]
    fn text_size(self) -> TextSize {
        let len = self.len();
        if let Ok(size) = len.try_into() {
            size
        } else if cfg!(debug_assertions) {
            panic!("overflow when converting to TextSize");
        } else {
            TextSize(len as u32)
        }
    }
}
```

This differs from the live `TextUnit::of_str`, which always panics for strings longer than `u32::max_value()`. The equivalent behavior would then be

```rust
impl TextSized for &'_ str {
    fn text_size(self) -> TextSize {
        self.len()
            .try_into()
            .unwrap_or_else(|_| panic!("string is too long for TextSize"))
    }
}
```

`TextSize` is deliberately limited to the fairly logical (for today) 4GiB of text. (For a sense of scale, the `src` directory of rust-lang/rust is ~800MiB with all submodules, and my entire rust-lang/rust folder minus build folder is ~3GiB.)

The question of whether `TextSize::of(&str)` should enforce this with debug assertions off is one of whether we should enforce this or expect the next layer up to enforce it. I currently think we should adjust this to always panic for a string larger than `TextSize::MAX`.

**Comment by matklad** [comment]
+1 to always panicking. 

This is a comparatively rare operation, so we won't be meaningfully faster by wrapping in a release.
